### ISSUE TITLE
Calling goBack multiple times break the navigation bar

### ISSUE THREAD

**Issue by rebaz94** [echedev/theseus-navigator#15]
Hi
When I call ```goBack``` on navigator multiple times, it will break the navigation bar and only shows ```#```

here is video explaining how issue appear

https://user-images.githubusercontent.com/11982812/144722106-149794e3-21b3-4089-b0a2-94391eb5d965.mov

I used the same code in example app just add ```leading``` to ```AppBar``` in ```CategoryListScreen```
```dart
leading: BackButton(
    onPressed: () {
    catalogNavigator.goBack();
  },
),
```

**Comment by echedev** [comment]
@rebaz94 Thank you for reporting the issue.
It should be fixed in #16
