### ISSUE TITLE
How to return and get value when pop to previous screen ?

### ISSUE THREAD

**Issue by MaheshPeri19** [echedev/theseus-navigator#21]
I push from screen 1 to screen to using goTo() and going back to previous screen using goBack(). Both are returning void only.

How can i send data from 2nd screen to 1st screen while pop and how to receive data at screen 1 ?

Please suggest me on this.

**Comment by echedev** [comment]
Returning result on going back is not supported at the moment. It is in the list of future improvements though.
Currently, the possible solution could be like saving the data in your app state on the 2nd screen, and listen that state on the 1st screen.

**Comment by MaheshPeri19** [comment]
Okay. Thank you.
